In [1]:
import numpy as np
import pandas as pd
import random
import math
import time

### Задание №1

Случайная непрерывная величина A имеет равномерное распределение на промежутке (200, 800]. 
Найдите ее среднее значение и дисперсию.

In [2]:
a = 201
b = 800

In [3]:
# Среднее значение
mean = (a + b)/2
mean

500.5

In [4]:
# Дисперсия
dispersion = (a - b)**2 / 12
dispersion

29900.083333333332

### Задание №2

О случайной непрерывной равномерно распределенной величине B известно, что ее дисперсия равна 0.2.
Можно ли найти правую границу величины B и ее среднее значение зная, что левая граница равна 0.5?
Если да, найдите ее.

In [5]:
dispersion = 0.2
a = 0.5

In [6]:
# Правая граница
b = np.sqrt(12 * dispersion) + a
b

2.049193338482967

In [7]:
# Среднее значение
mean = (a + b)/2
mean

1.2745966692414834

### Задание №3

Непрерывная случайная величина X распределена нормально и задана плотностью распределения
f(x) = (1 / (4 * sqrt(2*pi))) * (exp(-(x+2)**2) / 32).
Найдите:

а). M(X)

б). D(X)

в). std(X) (среднее квадратичное отклонение)

Такая общая формула плотность распределения имеет вид:

$$f(x) = \frac{1}{\sigma \sqrt{2 \pi}} e ^ {- \frac{(x - a)^2}{2 \sigma^2}}$$

А наша плотность распределения задана:

$$f(x) = \frac{1}{4\sqrt{2 \pi}} e ^ {- \frac{(x + 2)^2}{32}}$$

И зная, что:
    $$a = M(X)$$
    $$\sigma^2 = D(X)$$

Получаем:
    $$M(X) = -2$$
    $$D(X) = 4^2 = 32/2 = 16$$
    $$std(X) = \sqrt{D(X)}= 4$$

### Задание №4

Рост взрослого населения города X имеет нормальное распределение. 
Причем, средний рост равен 174 см, а среднее квадратичное отклонение равно 8 см.
Какова вероятность того, что случайным образом выбранный взрослый человек имеет рост:

а). больше 182 см

б). больше 190 см

в). от 166 см до 190 см

г). от 166 см до 182 см

д). от 158 см до 190 см

е). не выше 150 см или не ниже 190 см

ё). не выше 150 см или не ниже 198 см

ж). ниже 166 см.


In [8]:
M = 174
X_std = 8

In [9]:
print(f"M - sigma = {M - X_std}")
print(f"M - 2*sigma = {M - 2*X_std}")
print(f"M - 3*sigma = {M - 3*X_std}")
print(f"M + sigma = {M + X_std}")
print(f"M + 2*sigma = {M + 2*X_std}")
print(f"M + 3*sigma = {M + 3*X_std}")

M - sigma = 166
M - 2*sigma = 158
M - 3*sigma = 150
M + sigma = 182
M + 2*sigma = 190
M + 3*sigma = 198


In [10]:
# Вероятность больше или меньше 3*sigma:
sigma_3 = (100 - 99.73)/2
sigma_3

0.134999999999998

а). больше 182 см

In [11]:
(13.59 + 2.14 + sigma_3)/100

0.15864999999999999

б). больше 190 см

In [12]:
(2.14 + sigma_3)/100

0.022749999999999982

в). от 166 см до 190 см

In [13]:
(34.13 + 34.13 + 13.59)/100

0.8185000000000001

г). от 166 см до 182 см

In [14]:
(34.13 + 34.13)/100

0.6826000000000001

д). от 158 см до 190 см

In [15]:
(13.59 + 34.13 + 34.13 + 13.59)/100

0.9544

е). не выше 150 см или не ниже 190 см

In [16]:
(100 - (2.14 + 13.59 + 34.13 + 34.13 + 13.59))/100

0.024199999999999874

ё). не выше 150 см или не ниже 198 см

In [17]:
(100 - (2.14 + 13.59 + 34.13 + 34.13 + 13.59 + 2.14))/100

0.0027999999999998694

ж). ниже 166 см

In [18]:
(sigma_3 + 2.14 + 13.59)/100

0.15864999999999999

### Задание №5

На сколько сигм (средних квадратичных отклонений) отклоняется рост человека, равный 190 см, от 
математического ожидания роста в популяции, в которой M(X) = 178 см и D(X) = 25 кв.см?

In [19]:
M = 178
D = 25

In [20]:
X_std = np.sqrt(D)
X_std

5.0

In [21]:
np.abs(190 - M)/X_std

2.4